global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s  
  external_labels:
    monitor: task_monitoring

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 127.0.0.1:9093
      scheme: http
      timeout: 10s
      api_version: v1

rule_files:
  - rules.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'

  - job_name: 'netdata'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/api/v1/allmetrics'
    scheme: http
    params:
      format: [prometheus]
    honor_labels: true
    static_configs:
      - targets: ['localhost:19999']
        labels:
          instance: 'netdata'
 
  - job_name: 'node_exporter'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'node_exporter'

  - job_name: 'minio'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['localhost:9000']
        labels:
          instance: 'minio'
    
  - job_name: 'redis_exporter'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9121']
        labels:
          instance: 'redis_exporter'
          redis_port: '6379'